import React, { useState } from 'react';
import {
  Recycle,
  AlertTriangle,
  Lightbulb,
  CheckCircle2,
  Copy,
  Check,
  Leaf,
  Layers,
  Sparkles,
  Clock,
  ArrowUpRight,
  Info,
  ShieldAlert,
  Flame,
  FileText,
  RotateCcw,
} from 'lucide-react';
import { WasteAnalysisResult } from '../types/waste';

interface AnalysisResultProps {
  result: WasteAnalysisResult;
  stagedImage: string | null;
  onReset: () => void;
}

export const AnalysisResult: React.FC<AnalysisResultProps> = ({
  result,
  stagedImage,
  onReset,
}) => {
  const [copiedType, setCopiedType] = useState<'json' | 'markdown' | null>(null);

  const getCategoryColor = (cat: string) => {
    const c = cat.toLowerCase();
    if (c.includes('cardboard') || c.includes('paper')) {
      return {
        badge: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
        ring: 'from-amber-500 to-yellow-600',
        binBg: 'bg-amber-950/40 border-amber-800/60',
      };
    }
    if (c.includes('plastic')) {
      return {
        badge: 'bg-sky-500/10 text-sky-400 border-sky-500/30',
        ring: 'from-sky-500 to-blue-600',
        binBg: 'bg-sky-950/40 border-sky-800/60',
      };
    }
    if (c.includes('metal')) {
      return {
        badge: 'bg-rose-500/10 text-rose-400 border-rose-500/30',
        ring: 'from-rose-500 to-red-600',
        binBg: 'bg-rose-950/40 border-rose-800/60',
      };
    }
    if (c.includes('glass')) {
      return {
        badge: 'bg-yellow-500/10 text-yellow-300 border-yellow-500/30',
        ring: 'from-yellow-500 to-amber-600',
        binBg: 'bg-yellow-950/40 border-yellow-800/60',
      };
    }
    if (c.includes('electronic') || c.includes('e-waste')) {
      return {
        badge: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30',
        ring: 'from-emerald-500 to-teal-600',
        binBg: 'bg-emerald-950/40 border-emerald-800/60',
      };
    }
    if (c.includes('construction') || c.includes('debris') || c.includes('c&d')) {
      return {
        badge: 'bg-slate-400/10 text-slate-300 border-slate-500/30',
        ring: 'from-slate-400 to-stone-500',
        binBg: 'bg-slate-900 border-slate-700',
      };
    }
    if (c.includes('textile') || c.includes('garment') || c.includes('clothing')) {
      return {
        badge: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/30',
        ring: 'from-indigo-500 to-violet-600',
        binBg: 'bg-indigo-950/40 border-indigo-800/60',
      };
    }
    if (c.includes('organic') || c.includes('food') || c.includes('compost')) {
      return {
        badge: 'bg-green-500/10 text-green-400 border-green-500/30',
        ring: 'from-green-500 to-emerald-600',
        binBg: 'bg-green-950/40 border-green-800/60',
      };
    }
    return {
      badge: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/30',
      ring: 'from-cyan-500 to-blue-600',
      binBg: 'bg-cyan-950/40 border-cyan-800/60',
    };
  };

  const colors = getCategoryColor(result.wasteCategory);

  const handleCopy = (type: 'json' | 'markdown') => {
    let text = '';
    if (type === 'json') {
      text = JSON.stringify(result, null, 2);
    } else {
      text = `# VLM Waste Identification: ${result.objectName}
- **Material**: ${result.material} (${result.materialSubtype || 'Standard'})
- **Category**: ${result.wasteCategory}
- **Condition**: ${result.condition}
- **Confidence**: ${result.confidenceScore}%
- **Recyclability**: ${result.recyclabilityRating}

## Visual Reasoning
${result.reasoning}

## Recommended Disposal
**Method**: ${result.disposalMethod}
**Bin Color**: ${result.binColorCode}
**Action Steps**:
${result.disposalSteps.map((s, idx) => `${idx + 1}. ${s}`).join('\n')}

**Contamination Risks**:
${result.contaminationRisks}

## Reuse & Upcycling
${result.reuseAndUpcycling.map((u) => `- **${u.title}** (${u.difficulty}): ${u.description}`).join('\n')}

## Environmental Impact
- **Decomposition**: ${result.environmentalImpact.decompositionTime}
- **Embodied Carbon Note**: ${result.environmentalImpact.carbonFootprintNote}
- **Circular Economy Potential**: ${result.environmentalImpact.circularEconomyPotential}

*Generated by EcoLens Multimodal VLM (Gemini 3.8 Flash)*`;
    }

    navigator.clipboard.writeText(text);
    setCopiedType(type);
    setTimeout(() => setCopiedType(null), 2000);
  };

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Top Banner Card: Primary Identification */}
      <div className="relative overflow-hidden bg-slate-900 border border-slate-800 rounded-3xl p-6 sm:p-8 shadow-2xl">
        <div className={`absolute top-0 left-0 right-0 h-1.5 bg-gradient-to-r ${colors.ring}`} />

        <div className="flex flex-col lg:flex-row gap-6 lg:items-start justify-between">
          <div className="space-y-4 max-w-3xl">
            {/* Meta Tags */}
            <div className="flex flex-wrap items-center gap-2">
              <span className={`text-xs px-3 py-1 rounded-full font-semibold border ${colors.badge}`}>
                {result.wasteCategory}
              </span>
              {result.materialSubtype && (
                <span className="text-xs px-2.5 py-0.5 rounded-full bg-slate-800 text-slate-300 border border-slate-700 font-mono">
                  {result.materialSubtype}
                </span>
              )}
              <span className="text-xs px-2.5 py-0.5 rounded-full bg-slate-800/80 text-slate-400 border border-slate-700/80">
                Condition: <strong className="text-slate-200">{result.condition}</strong>
              </span>
              <div className="flex items-center space-x-1 text-xs text-emerald-400 bg-emerald-500/10 px-2.5 py-0.5 rounded-full border border-emerald-500/20">
                <CheckCircle2 className="w-3.5 h-3.5" />
                <span>{result.confidenceScore}% Confidence</span>
              </div>
            </div>

            {/* Object Title & Material Breakdown */}
            <div>
              <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
                {result.objectName}
              </h1>
              <div className="mt-2 flex items-center space-x-2 text-sm sm:text-base text-slate-300">
                <span className="text-slate-500 font-mono text-xs uppercase tracking-wider">Identified Material:</span>
                <span className="font-semibold text-emerald-400 bg-emerald-950/40 px-2.5 py-0.5 rounded-md border border-emerald-800/50">
                  {result.material}
                </span>
              </div>
            </div>

            {/* Executive Summary */}
            <p className="text-sm text-slate-300 leading-relaxed bg-slate-950/60 p-4 rounded-2xl border border-slate-800/80">
              {result.summary}
            </p>
          </div>

          {/* Quick Stats Column / Image Thumbnail */}
          <div className="flex flex-row lg:flex-col gap-3 lg:w-64 shrink-0">
            {stagedImage && (
              <div className="w-24 h-24 lg:w-full lg:h-36 rounded-2xl overflow-hidden bg-slate-950 border border-slate-800 shrink-0">
                <img
                  src={stagedImage}
                  alt="Scanned specimen"
                  className="w-full h-full object-cover"
                />
              </div>
            )}

            <div className="flex-1 bg-slate-950/80 p-3.5 rounded-2xl border border-slate-800/90 flex flex-col justify-between">
              <div>
                <span className="text-[11px] font-mono uppercase text-slate-500 tracking-wider">
                  Recyclability Index
                </span>
                <p className="text-sm font-bold text-white mt-0.5 flex items-center space-x-1.5">
                  <Recycle className="w-4 h-4 text-emerald-400" />
                  <span>{result.recyclabilityRating}</span>
                </p>
              </div>

              <div className="mt-2.5 pt-2.5 border-t border-slate-800/80 flex items-center justify-between text-xs text-slate-400">
                <span>Recommended Bin</span>
                <span className="font-medium text-slate-200">{result.binColorCode.split(' ')[0]}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Action Controls Bar */}
        <div className="mt-6 pt-5 border-t border-slate-800 flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center space-x-2">
            <button
              onClick={() => handleCopy('markdown')}
              className="flex items-center space-x-1.5 text-xs text-slate-300 hover:text-white bg-slate-800 hover:bg-slate-700 px-3 py-1.5 rounded-lg border border-slate-700 transition"
              title="Copy formatted markdown report"
            >
              {copiedType === 'markdown' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <FileText className="w-3.5 h-3.5" />}
              <span>{copiedType === 'markdown' ? 'Copied MD' : 'Copy Report'}</span>
            </button>

            <button
              onClick={() => handleCopy('json')}
              className="flex items-center space-x-1.5 text-xs text-slate-300 hover:text-white bg-slate-800 hover:bg-slate-700 px-3 py-1.5 rounded-lg border border-slate-700 transition"
              title="Copy raw JSON"
            >
              {copiedType === 'json' ? <Check className="w-3.5 h-3.5 text-cyan-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedType === 'json' ? 'Copied JSON' : 'JSON'}</span>
            </button>
          </div>

          <button
            onClick={onReset}
            className="flex items-center space-x-1.5 text-xs font-semibold text-slate-200 hover:text-white bg-emerald-600/80 hover:bg-emerald-600 px-4 py-2 rounded-xl transition shadow-md shadow-emerald-900/30"
          >
            <RotateCcw className="w-3.5 h-3.5" />
            <span>Scan Another Specimen</span>
          </button>
        </div>
      </div>

      {/* Grid: Reasoning + Disposal Protocol */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 sm:gap-8">
        {/* CARD 1: VLM Visual Reasoning */}
        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 sm:p-7 shadow-xl flex flex-col justify-between">
          <div>
            <div className="flex items-center space-x-3 mb-4">
              <div className="w-9 h-9 rounded-xl bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 flex items-center justify-center">
                <Sparkles className="w-5 h-5" />
              </div>
              <div>
                <h2 className="text-base font-bold text-white tracking-tight">VLM Perceptual Reasoning</h2>
                <p className="text-xs text-slate-400">Micro-features, surface texture, and optical signatures</p>
              </div>
            </div>

            <div className="bg-slate-950/70 border border-slate-800/80 rounded-2xl p-4 text-sm text-slate-300 leading-relaxed whitespace-pre-line">
              {result.reasoning}
            </div>

            {/* Secondary Components if detected */}
            {result.secondaryComponents && result.secondaryComponents.length > 0 && (
              <div className="mt-5 space-y-2.5">
                <span className="text-xs font-mono uppercase text-slate-400 flex items-center space-x-1.5">
                  <Layers className="w-3.5 h-3.5 text-amber-400" />
                  <span>Detected Multi-Material Components ({result.secondaryComponents.length})</span>
                </span>
                <div className="space-y-2">
                  {result.secondaryComponents.map((comp, idx) => (
                    <div
                      key={idx}
                      className="bg-slate-950/50 border border-slate-800 p-3 rounded-xl flex items-start justify-between text-xs gap-3"
                    >
                      <div>
                        <strong className="text-slate-200">{comp.componentName}</strong>
                        <span className="text-slate-400 block text-[11px] mt-0.5">
                          Material: {comp.material}
                        </span>
                      </div>
                      <span className="text-[11px] text-cyan-300 bg-cyan-950/50 px-2 py-1 rounded border border-cyan-800/40 text-right">
                        {comp.action}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          <div className="mt-6 pt-4 border-t border-slate-800/80 flex items-center text-[11px] text-slate-500">
            <Info className="w-3.5 h-3.5 mr-1.5 text-slate-400 shrink-0" />
            <span>Open-world visual analysis by Gemini 3.8 Flash multimodal reasoning engine.</span>
          </div>
        </div>

        {/* CARD 2: Recommended Disposal & Handling */}
        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 sm:p-7 shadow-xl flex flex-col justify-between">
          <div>
            <div className="flex items-center space-x-3 mb-4">
              <div className="w-9 h-9 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 flex items-center justify-center">
                <Recycle className="w-5 h-5" />
              </div>
              <div>
                <h2 className="text-base font-bold text-white tracking-tight">Recommended Disposal Channel</h2>
                <p className="text-xs text-slate-400">Preparation steps and target recovery stream</p>
              </div>
            </div>

            {/* Target Bin & Method Banner */}
            <div className={`p-4 rounded-2xl border mb-4 ${colors.binBg}`}>
              <div className="flex items-start justify-between gap-3">
                <div>
                  <span className="text-[10px] font-mono uppercase tracking-wider text-slate-400">
                    Primary Route
                  </span>
                  <h3 className="text-base font-bold text-white mt-0.5">{result.disposalMethod}</h3>
                </div>
                <div className="text-right">
                  <span className="text-[10px] font-mono uppercase tracking-wider text-slate-400">
                    Target Bin
                  </span>
                  <div className="text-xs font-semibold text-slate-200 mt-0.5 bg-slate-900/80 px-2.5 py-1 rounded-md border border-slate-700">
                    {result.binColorCode}
                  </div>
                </div>
              </div>
            </div>

            {/* Actionable Steps */}
            <div className="space-y-2 mb-4">
              <span className="text-xs font-mono uppercase text-slate-400">
                Actionable Preparation Steps:
              </span>
              <ol className="space-y-2">
                {result.disposalSteps.map((step, idx) => (
                  <li
                    key={idx}
                    className="flex items-start space-x-2.5 text-xs text-slate-300 bg-slate-950/60 p-2.5 rounded-xl border border-slate-800/80"
                  >
                    <span className="w-5 h-5 rounded-full bg-slate-800 text-emerald-400 font-mono text-[11px] font-bold flex items-center justify-center shrink-0">
                      {idx + 1}
                    </span>
                    <span className="leading-snug pt-0.5">{step}</span>
                  </li>
                ))}
              </ol>
            </div>

            {/* Contamination Alert */}
            <div className="bg-red-500/10 border border-red-500/25 rounded-2xl p-3.5 flex items-start space-x-3 text-xs text-red-300">
              <ShieldAlert className="w-4 h-4 text-red-400 shrink-0 mt-0.5" />
              <div>
                <strong className="text-red-200 block mb-0.5">Stream Contamination Hazard:</strong>
                <span>{result.contaminationRisks}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Grid: Reuse/Upcycling + Ecological Lifecycle */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 sm:gap-8">
        {/* Reuse & Upcycling Ideas */}
        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 sm:p-7 shadow-xl">
          <div className="flex items-center space-x-3 mb-5">
            <div className="w-9 h-9 rounded-xl bg-amber-500/10 border border-amber-500/20 text-amber-400 flex items-center justify-center">
              <Lightbulb className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white tracking-tight">Reuse & Upcycling Pathways</h2>
              <p className="text-xs text-slate-400">Diverting material from waste streams through creative second life</p>
            </div>
          </div>

          <div className="space-y-3">
            {result.reuseAndUpcycling.map((idea, idx) => (
              <div
                key={idx}
                className="bg-slate-950/80 border border-slate-800 hover:border-slate-700 rounded-2xl p-4 transition"
              >
                <div className="flex items-center justify-between mb-1.5">
                  <h3 className="text-xs sm:text-sm font-bold text-white">{idea.title}</h3>
                  <span
                    className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${
                      idea.difficulty.toLowerCase().includes('beginner') || idea.difficulty.toLowerCase().includes('easy')
                        ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20'
                        : idea.difficulty.toLowerCase().includes('intermediate')
                        ? 'bg-amber-500/10 text-amber-400 border border-amber-500/20'
                        : 'bg-purple-500/10 text-purple-400 border border-purple-500/20'
                    }`}
                  >
                    {idea.difficulty}
                  </span>
                </div>
                <p className="text-xs text-slate-400 leading-relaxed">{idea.description}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Environmental Lifecycle & Circular Economy */}
        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 sm:p-7 shadow-xl flex flex-col justify-between">
          <div>
            <div className="flex items-center space-x-3 mb-5">
              <div className="w-9 h-9 rounded-xl bg-teal-500/10 border border-teal-500/20 text-teal-400 flex items-center justify-center">
                <Leaf className="w-5 h-5" />
              </div>
              <div>
                <h2 className="text-base font-bold text-white tracking-tight">Circular Lifecycle & Ecological Impact</h2>
                <p className="text-xs text-slate-400">Natural degradation timeline and embodied carbon metrics</p>
              </div>
            </div>

            <div className="space-y-4">
              {/* Decomposition Time */}
              <div className="bg-slate-950/80 border border-slate-800 p-4 rounded-2xl flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <div className="w-8 h-8 rounded-lg bg-slate-800 flex items-center justify-center text-slate-300">
                    <Clock className="w-4 h-4 text-cyan-400" />
                  </div>
                  <div>
                    <span className="text-[11px] text-slate-400 font-mono uppercase">Decomposition Horizon</span>
                    <p className="text-sm font-bold text-white">
                      {result.environmentalImpact.decompositionTime}
                    </p>
                  </div>
                </div>
                <span className="text-xs text-slate-500">Natural Environment</span>
              </div>

              {/* Carbon Footprint */}
              <div className="bg-slate-950/80 border border-slate-800 p-4 rounded-2xl space-y-1">
                <div className="flex items-center space-x-2 text-xs font-semibold text-slate-300">
                  <Flame className="w-4 h-4 text-rose-400" />
                  <span>Embodied Energy & Carbon Assessment</span>
                </div>
                <p className="text-xs text-slate-400 leading-relaxed pl-6">
                  {result.environmentalImpact.carbonFootprintNote}
                </p>
              </div>

              {/* Circular Economy Potential */}
              <div className="bg-slate-950/80 border border-slate-800 p-4 rounded-2xl space-y-1">
                <div className="flex items-center space-x-2 text-xs font-semibold text-slate-300">
                  <Recycle className="w-4 h-4 text-emerald-400" />
                  <span>Closed-Loop Circularity</span>
                </div>
                <p className="text-xs text-slate-400 leading-relaxed pl-6">
                  {result.environmentalImpact.circularEconomyPotential}
                </p>
              </div>
            </div>
          </div>

          <div className="mt-6 pt-4 border-t border-slate-800/80 flex items-center justify-between text-xs text-slate-500">
            <span>Model: Gemini 3.8 Flash Multimodal VLM</span>
            <span className="text-emerald-400 font-medium">Empirical Identification</span>
          </div>
        </div>
      </div>
    </div>
  );
};
